#开发环境配置

#数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456


#Mybatis配置
#mybatis:
#  type-aliases-package: pers.hong.project.entity
#  mapper-locations: classpath:mapper/*.xml

#Pagehelper配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  page-size-zero: true
